services:
  mysql:
    image: mysql:8.0
    container_name: dayum-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-dayum2}
      MYSQL_USER: ${DB_USERNAME:-dayum2}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dayum2_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dayum-network

volumes:
  mysql_data:
    driver: local

networks:
  dayum-network:
    driver: bridge 
