# Server Configuration
server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: dayum-server
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/dayum
    username: dayum2
    password: dayum2_password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-secretsmanager:dayum/server/prod'

  cloud.aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${ACCESS_TOKEN}
      secret-key: ${SECRET_TOKEN}

  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/dayum
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
