name: deploy

on:
  push:
    branches:
      - chanjun.park_github_action_cicd
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SERVER_SSH_PORT || 22 }}" -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
      - name: Run bootstrap via SSH
        uses: appleboy/ssh-action@v1
        env:
          AWS_ACCESS_TOKEN: ${{ secrets.AWS_ACCESS_TOKEN }}
          AWS_SECRET_TOKEN: ${{ secrets.AWS_SECRET_TOKEN }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT || 22 }}
          envs: AWS_ACCESS_TOKEN,AWS_SECRET_TOKEN
          script_stop: true
          script: |
            set -euo pipefail
            bash -lc "~/bootstrap.sh"
#  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - uses: docker/login-action@v3
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - id: vars
#        run: echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
#      - uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: |
#            ${{ env.IMAGE_NAME }}:latest
#            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHA7 }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max